default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_47728_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_47728_test
  prepared_statements: false
  pool: 10
  checkout_timeout: 10

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>